variables:
    project_name: shoe-ShoppingCart
    project_version: 0.0.1-SNAPSHOT
    project_user: shoeshop
    project_path: /datas/shoeshop/
    
stages:
    - build
    - deploy
    - showlog

build:
    stage: build
    variables:
        GIT_STRATEGY: clone
    script:
        - mvn install -DskipTests=true
    tags:
        - dev-server
    only:
        - tags

deploy:
    stage: deploy
    variables:
        GIT_STRATEGY: none
    when: manual
    script:
        - >
            if [ "$GITLAB_USER_LOGIN" == 'huancd' ]; then
                sudo cp target/$project_name-$project_version.jar $project_path
                pwd
                ls -l
                sudo chown -R $project_user. $project_path
                pwd
                ls -l
                sudo chmod -R 750 $project_path
                pwd
                ls -l
                whoami
                sudo su $project_user -c "kill -9 $(ps -ef | grep $project_name-$project_version.jar | grep -v grep | awk '{print $2}')"
                sudo su $project_user -c "cd $project_path; nohup java -jar $project_name-$project_version.jar > nohup.out 2>&1 &"
            else
                echo "Permission denied"
                exit 1
            fi

    tags:
        - dev-server
    only:
        - tags

showlog:
    stage: showlog
    variables:
        GIT_STRATEGY: none
    when: manual

    script:
        - sudo su $project_user -c "cd $project_path; tail -n 10000 nohup.out"
    
    tags:
        - dev-server
    only:
        - tags
